# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-03 20:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
                ('localizacao', models.CharField(max_length=128)),
                ('logo', models.CharField(max_length=100)),
                ('contacto', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('data_criacao', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_abreviado', models.CharField(max_length=50)),
                ('nome', models.CharField(max_length=200)),
                ('preco', models.CharField(max_length=20)),
                ('imagem', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barato.Fornecedor')),
            ],
        ),
    ]
