# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-07 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barato', '0002_auto_20161103_2253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='nome_abreviado',
        ),
        migrations.AddField(
            model_name='produto',
            name='nome_long',
            field=models.CharField(default='nome longo', max_length=200),
        ),
    ]
