# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-07 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barato', '0003_auto_20161107_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='nome_long',
            field=models.CharField(max_length=200),
        ),
    ]
